name: Deploy to Beget

on:
  push:
    branches:
      - main # ветка, от которой деплой

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repository on server
        run: |
          echo "$SSH_PRIVATE_KEY" | ssh -o StrictHostKeyChecking=no -i /dev/stdin svstenew_deployuser@svstenew.beget.tech "echo git pull"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_SECRET }}
