name: Deploy to Beget

on:
  push:
    branches:
      - main # ветка, от которой деплой

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repository on server
        run: |
          ssh -o StrictHostKeyChecking=no -i secrets.SSH_KEY  svstenew_deployuser@svstenew.beget.tech \
          "git fetch origin && git reset --hard origin/main"
